apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      nodeSelector:
        kubernetes.io/hostname: worker1
      # Thêm initContainers để đảm bảo quyền cho volume
      initContainers:
      - name: volume-permissions
        image: busybox
        command: ["sh", "-c", "chmod -R 777 /data/db"]
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
      containers:
      - name: mongodb
        image: tonytran1997/mongo-app:staging-latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
      volumes:
      - name: mongo-persistent-storage
        persistentVolumeClaim:
          claimName: mongo-pvc
