apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: staging
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
  # type: LoadBalancer
  # ports:
  #   - port: 27017
  #     targetPort: 27017
  #     protocol: TCP
  # type: NodePort
  # ports:
  #   - port: 27017
  #     targetPort: 27017
  #     protocol: TCP
  #     nodePort: 32000
  selector:
    app: mongodb
